version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: upload/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: upload/app.docker
        volumes:
            - ./:/var/www
    